import Image from "../../../Assets/Images/alumni.jpg";
const Alumni = [
  {
    id: 1,
    year: 2022,
    image: { Image },
    name: "Yashvi",
    linkedIn: "https://www.linkedin.com/",
  },

  {
    id: 2,
    year: 2022,
    image: "../../../Assets/Images/alumni.jpg",
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 3,
    year: 2022,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },

  {
    id: 4,
    year: 2022,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },

  {
    id: 5,
    year: 2022,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 6,
    year: 2022,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 7,
    year: 2021,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 8,
    year: 2021,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 9,
    year: 2021,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 10,
    year: 2021,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 11,
    year: 2021,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 12,
    year: 2020,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 13,
    year: 2020,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 14,
    year: 2020,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 15,
    year: 2020,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 16,
    year: 2020,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 17,
    year: 2019,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 18,
    year: 2019,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 19,
    year: 2019,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 20,
    year: 2019,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 21,
    year: 2018,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 22,
    year: 2018,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 23,
    year: 2018,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 24,
    year: 2018,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 25,
    year: 2018,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 26,
    year: 2017,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 27,
    year: 2017,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 28,
    year: 2017,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 29,
    year: 2017,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 30,
    year: 2017,
    image: require("../../../Assets/Images/alumni.jpg").default,
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 31,
    year: 2016,
    image: {Image},
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
  {
    id: 32,
    year: 2016,
    image: {Image},
    name: "xyz",
    linkedIn: "https://www.linkedin.com/",
  },
];

export default Alumni;
